const GET_TASKS = 'GET_TASKS'
const ADD_TASK = 'ADD_TASK'
const DELETE_TASK = 'DELETE_TASK'
const UPDATE_TASK = 'UPDATE_TASK'
const EDITED_TASK = 'EDITED_TASK'

export { GET_TASKS, ADD_TASK, DELETE_TASK, UPDATE_TASK, EDITED_TASK }